name: eds
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0=py_1
  - attrs=20.2.0=pyh9f0ad1d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=pyh9f0ad1d_0
  - branca=0.4.1=py_0
  - brotlipy=0.7.0=py37h4ab8f01_1000
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.1=py37h26f1ce3_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - colorama=0.4.3=py_0
  - cryptography=3.1=py37h26f1ce3_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37hc8dfbb8_1001
  - folium=0.10.0=py_0
  - freetype=2.10.2=hd328e21_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=67.1=h33f27b4_0
  - idna=2.10=pyh9f0ad1d_0
  - imbalanced-learn=0.4.3=py_0
  - importlib-metadata=1.7.0=py37hc8dfbb8_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2019.4=245
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.18.1=py37hc6149b9_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.14.0=py37_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=he774522_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter_client=6.1.7=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py37_0
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - jupyter_highlight_selected_word=0.2.0=py37_1000
  - jupyter_latex_envs=1.4.4=py37_1000
  - jupyter_nbextensions_configurator=0.4.1=py37_0
  - kiwisolver=1.2.0=py37heaa310e_0
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libclang=10.0.1=default_hf44288c_1
  - libiconv=1.16=he774522_0
  - liblapack=3.8.0=14_mkl
  - libpng=1.6.37=ha81a0f5_2
  - libsodium=1.0.17=h2fa13f4_0
  - libxml2=2.9.10=h1006b36_2
  - libxslt=1.1.33=h579f668_1
  - lxml=4.5.2=py37h8ba8a40_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py37h8055547_1
  - matplotlib=3.0.3=py37_1
  - matplotlib-base=3.0.3=py37h3e3dc42_1
  - mistune=0.8.4=py37h8055547_1001
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hfa6e2cd_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.7=py_0
  - notebook=5.7.8=py37_1
  - numpy=1.16.4=py37hc71023c_0
  - openssl=1.1.1g=he774522_1
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=0.24.2=py37he350917_0
  - pandoc=2.10.1=he774522_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.0=pyh9f0ad1d_0
  - patsy=0.5.1=py_0
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pip=20.2.2=py_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37h6538335_1
  - pyrsistent=0.16.0=py37h8055547_0
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.3=h510b542_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - pywin32=227=py37hfa6e2cd_0
  - pywinpty=0.5.7=py37_0
  - pyyaml=5.3.1=py37h8055547_0
  - pyzmq=19.0.2=py37h453f00a_0
  - qt=5.12.6=hb2cf2c5_0
  - requests=2.24.0=pyh9f0ad1d_0
  - scikit-learn=0.20.3=py37h3d241f0_1
  - scipy=1.5.2=py37h9439919_0
  - seaborn=0.9.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py37hc8dfbb8_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=he774522_0
  - statsmodels=0.12.0=py37h4ab8f01_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37hfa6e2cd_0
  - traitlets=5.0.4=py_0
  - urllib3=1.25.10=py_0
  - vc=14.1=h869be7e_1
  - vincent=0.4.4=py_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - wcwidth=0.2.5=pyh9f0ad1d_1
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_1003
  - winpty=0.4.3=4
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.2=ha925a31_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h62dcd97_1009
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: C:\Users\zunic\Miniconda3\envs\eds
